### ISSUE TITLE
Why not use built in two way binding?

### ISSUE THREAD

**Issue by etcook** [kaihenzler/angular-minicolors#14]
Out of curiosity, why didn't you just leverage the native two-way binding on an input field?

**Comment by kaihenzler** [comment]
Hello there,

sorry for the late response.
I need to watch for changes inside the jQuery Plugin by using its 'change' method because I didn't got it to work in any other way.
Also there were issues when I wanted to set an initial value, but I can't really remember why exactly I did it the way I did it.
