### ISSUE TITLE
Error when used in dynamically compiled directive

### ISSUE THREAD

**Issue by vz28bh** [kaihenzler/angular-minicolors#38]
I have an app that uses a variable to decide what type of directive to show.  There is a parent directive that compiles the correct one based on the value of the variable. It works fine except that the angular-minicolors is not happy. I found an issue at minicolors that seemed related, which made me think that something in the recompiling process is not destroying/initializing the jquery object correctly.

https://github.com/claviska/jquery-minicolors/issues/117

I don't have any other info so closing this issue is OK if it isn't obvious what the problem is, but I wanted to leave an FYI.

<pre>
TypeError: Cannot read property 'letterCase' of undefined
    at e (jquery.minicolors.min.js:11)
    at HTMLInputElement.<anonymous> (jquery.minicolors.min.js:11)
    at Function.each (jquery-1.10.2.min.js:4)
    at init.each (jquery-1.10.2.min.js:4)
    at init.minicolors (jquery.minicolors.min.js:11)
    at angular-minicolors.js:63
    at angular.js:19157
    at completeOutstandingRequest (angular.js:5869)
    at angular.js:6145
</pre>

**Comment by vz28bh** [comment]
Thought I would add a comment that the error may be caused by forgetting to destroy the scope when recompiling the directive. I will test when I have a chance.

**Comment by kaihenzler** [comment]
could you provide a jsfiddle or so to demonstrate the issue? This directive does not create its own child scope but uses the parentScope. There is no "scope" property in the directive definition object. I don't quite know what exactly goes on there, but if you could provide an example I will most likely find out where the problem comes from.

btw: thanks for using this directive =)
